CRUD/CRUD-Alumnos/CRUD-Alumnos/Models/Alumnos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Alumnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int Edad { get; set; }
        public string Genero { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public int Cod_Ciudad { get; set; }
        public string Nombre { get; set; }
        public virtual Ciudad Ciudad { get; set; }
    }
}

CRUD/CRUD-Alumnos/CRUD-Alumnos/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRUD_Alumnos.Models;

namespace CRUD_Alumnos.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno
        public ActionResult Index()
        {
            try
            {
                using (var db = new AlumnosContext())
                {
                    var data = (from a in db.Alumnos
                               join c in db.Ciudad on a.Cod_Ciudad equals c.id
                               select new AlumnoCE()
                               {
                                   Id = a.Id,
                                   Nombres = a.Nombres,
                                   Apellidos = a.Apellidos,
                                   Edad = a.Edad,
                                   Genero = a.Genero,
                                   Cod_Ciudad = a.Cod_Ciudad,
                                   Fecha_Registro = a.Fecha_Registro,
                                   Nombre = c.Nombre

                               }).ToList();
                   
                    return View(data);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Error al editar alumno " + e.Message);
                return View();
            }
            //try
            //{
            //    using (var db = new AlumnosContext())
            //    {
            //        //filtro para mostrar solo los mayores a 18
            //        List<Alumnos> lista = db.Alumnos.Where(alumno => alumno.Edad > 18).ToList();
            //        //filtro
            //        List<Alumnos> listaOrdenada = db.Alumnos.OrderBy(alumno => alumno.Edad).ToList();
            //        //LINQ to SQL
            //        List<Alumnos> lista2 = (from a in db.Alumnos
            //                                orderby a.Edad descending
            //                                select a).ToList();

            //        return View(db.Alumnos.ToList());
            //    }
            //}
            //catch (Exception err)
            //{
            //    ModelState.AddModelError("", "Error al Cargar vista " + err.Message);
            //    return View();
            //}



        }

        public ActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(Alumnos A)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                try
                {
                    //metodo recomendado
                    using (var db = new AlumnosContext())
                    {
                        //Tenemos que agregar la fecha de registro
                        A.Fecha_Registro = DateTime.Now;
                        //para asegurar que la conexion no se quede abierta
                        db.Alumnos.Add(A);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("","Error al registrar alumno "+e.Message);
                    return View();
                }
                
            }
           
        }
        public ActionResult Agregar2()
        {
            return View();
        }
        public ActionResult ListaCiudades()
        {
            using (var db = new AlumnosContext())
            {
                return PartialView(db.Ciudad.ToList());
            }
        }
        public ActionResult MostrarCiudad(int id)
        {
            using (var db = new AlumnosContext())
            {
                return PartialView(db.Ciudad.Find(id));
            }
        }

        public ActionResult Editar(int id)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new AlumnosContext())
                {
                    //Alumnos al = db.Alumnos.Where(alum => alum.Id == id).FirstOrDefault();
                    Alumnos segundaforma = db.Alumnos.Find(id);//el find solo cuando se sabe que tiene una clave primaria
                    if (segundaforma != null)
                    {
                        return View(segundaforma);
                    }
                    else
                    {
                        ModelState.AddModelError("Error", "No se ha encontrado el alumno ");
                        return RedirectToAction("Index");
                    }
                   
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Error", "Error al editar alumno " + e.Message);
                return RedirectToAction("Index");
            }


        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Alumnos Alumn)
        {
            try
            {
                using (var db = new AlumnosContext())
                {

                    Alumnos editAlumno = db.Alumnos.Find(Alumn.Id);
                    if (editAlumno != null){
                        /// si existe
                        editAlumno.Nombres = Alumn.Nombres;
                        editAlumno.Apellidos = Alumn.Apellidos;
                        editAlumno.Edad = Alumn.Edad;
                        editAlumno.Genero = Alumn.Genero;
                        editAlumno.Cod_Ciudad = Alumn.Cod_Ciudad;

                        db.SaveChanges();
                        //redireccionamos al index
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Error al editar alumno ");
                        return View();
                    }
                }
                   
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Error al editar alumno " + e.Message);
                return View();
            }
          
        }

        public ActionResult DetallesAlumno(int id)
        {
            try
            {
                using (var db = new AlumnosContext())
                {
                    var data = (from a in db.Alumnos
                               join c in db.Ciudad on a.Cod_Ciudad equals c.id
                               where a.Id == id
                               select new AlumnoCE()
                               {
                                   Id = a.Id,
                                   Nombres = a.Nombres,
                                   Apellidos = a.Apellidos,
                                   Edad = a.Edad,
                                   Genero = a.Genero,
                                   Cod_Ciudad = a.Cod_Ciudad,
                                   Fecha_Registro = a.Fecha_Registro,
                                   Nombre = c.Nombre
                                   
                               }).SingleOrDefault(); //.SingleOrDefault<AlumnoCE>();
                    return View(data);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Error al editar alumno " + e.Message);
                return View();
            }
        }
        public ActionResult VerCiduad(int id)
        {
            try
            {
                using (var db = new AlumnosContext())
                {
                     Alumnos detalleAlumno = db.Alumnos.Find(id);
                    //var lista = from persona in db.Alumnos
                    //            join ciudad in db.Ciudad
                    //            on persona.Cod_Ciudad equals ciudad.id;

                    return View(detalleAlumno);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Error al editar alumno " + e.Message);
                return View();
            }
        }

        public ActionResult EliminarAlumno(int id)
        {
            try
            {
                using (var db = new AlumnosContext())
                {
                    Alumnos EliminarAlumno = db.Alumnos.Find(id);
                    db.Alumnos.Remove(EliminarAlumno);
                    db.SaveChanges();
                    //redireccionamos al index
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", "Error al editar alumno " + e.Message);
                return View();
            }
        }

        public static string NombreCiudad( int cod)
        {
            using (var db = new AlumnosContext())
            {
                return db.Ciudad.Find(cod).Nombre;
            }
        }
    }
}

CRUD/CRUD-Alumnos/CRUD-Alumnos/Views/Alumno/Agregar.cshtml
@model CRUD_Alumnos.Models.Alumnos

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Alumnos</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="Genero" name="Genero">
                <option value="H">Hombre</option>
                <option value="M">Mujer</option>
            </select>
            @*@Html.EditorFor(model => model.Genero, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cod_Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
           @Html.Action("ListaCiudades","Alumno")
            @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Agregar" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CRUD/CRUD-Alumnos/CRUD-Alumnos/Views/Alumno/Agregar2.cshtml
@model CRUD_Alumnos.Models.Alumnos

@{
    ViewBag.Title = "Agregar2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar2</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alumnos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Registro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Registro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Registro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cod_Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cod_Ciudad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cod_Ciudad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CRUD/CRUD-Alumnos/CRUD-Alumnos/Views/Alumno/DetallesAlumno.cshtml
@*@model CRUD_Alumnos.Models.Alumnos*@
@model CRUD_Alumnos.Models.AlumnoCE

@{
    ViewBag.Title = "DetallesAlumno";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DetallesAlumno</h2>

<div>
    <h4>Alumnos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre Completo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)

                @*@Html.DisplayFor(model => model.NombreCompleto)*@
         </dd>

        <dt>
            Apellidos
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            Edad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            Genero
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>

        <dt>
            Fecha de registro
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Registro)
        </dd>

        <dt>
            Ciudad
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
            @*@Html.Action("MostrarCiudad", "Alumno", new { id = Model.Cod_Ciudad })*@
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Editar", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CRUD/CRUD-Alumnos/CRUD-Alumnos/Views/Alumno/Editar.cshtml
@model CRUD_Alumnos.Models.Alumnos

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Alumnos</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.ValidationMessage("Error")
    <div class="form-group">
        @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <select class="form-control" id="Genero" name="Genero">
                <option value="H" @( Model.Genero == "H" ? "Selected" : "")>Hombre</option>
                <option value="M" @( Model.Genero == "M" ? "Selected" : "" )>Mujer</option>
            </select>
            @*@Html.EditorFor(model => model.Genero, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cod_Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Action("ListaCiudades", "Alumno")
            @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    $('#Cod_Ciudad').val("@Model.Cod_Ciudad");
</script>
}

CRUD/CRUD-Alumnos/CRUD-Alumnos/Views/Alumno/Index.cshtml
@model IEnumerable<CRUD_Alumnos.Models.AlumnoCE>

@{
    ViewBag.Title = "LIsta de alumnos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear nuevo", "Agregar")
</p>
<table class="table">
    <tr>
        <th>
            @* @Html.DisplayNameFor(model => model.Nombres)*@
            Nombre Completo
        </th>
        <th>
            Edad
        </th>
        <th>
            Género
        </th>
        <th>
            Ciudad
        </th>
        <th>
            Fecha de Registro
        </th>
        <th>Acciones</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCompleto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @{
                    if (item.Genero.Equals("H") || item.Genero.Equals("h"))
                    {
                        <span>Hombre</span>
                    }
                    else
                    {
                        <span>Mujer</span>
                    }
                }
            </td>
            <td>
                @*@CRUD_Alumnos.Controllers.AlumnoController.NombreCiudad(item.Cod_Ciudad)*@
                @item.Nombre
            </td>
            <td>
                @item.Fecha_Registro.ToShortDateString()
                @*@Html.DisplayFor(modelItem => item.Fecha_Registro)*@
            </td>
            <td>
                @*Estructura      Texto      ActionResult en el controlador      Parametro a enviar*@
                @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "DetallesAlumno", new { id = item.Id }) |
                @Html.ActionLink("Eliminar", "EliminarAlumno", new { id = item.Id }, new { @class = "aElimina" })
            </td>
        </tr>
    }

</table>
@section scripts{
    <script>
        $('.aElimina').click(function(event){
            if (!confirm('¿Seguro que quieres eliminar este usuario?')) {
                event.preventDefault();
            }
        });
    </script>
}

CRUD/CRUD-Alumnos/CRUD-Alumnos/Views/Alumno/ListaCiudades.cshtml
@model IEnumerable<CRUD_Alumnos.Models.Ciudad>

<select class="form-control" id="Cod_Ciudad" name="Cod_Ciudad">
    @foreach (var item in Model)
    {
        <option value="@item.id">@item.Nombre</option> //razor
    }
</select>

CRUD/CRUD-Alumnos/CRUD-Alumnos/Views/Alumno/MostrarCiudad.cshtml
@model CRUD_Alumnos.Models.Ciudad

            @Html.DisplayFor(model => model.Nombre)
      