WEB PROYECTOS/DEMO ASPNET MVC EN CAPAS/WEB_PROYECTOS/Controllers/DepartamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using ENTIDAD;
using NEGOCIO;

namespace WEB_PROYECTOS.Controllers
{
    public class DepartamentoController : Controller
    {
      
        // GET: Departamento
        public ActionResult Index()
        {
            var dptos = DepartamentoCN.ListarDepartamentos();
            return View(dptos);
        }
        [HttpGet] //cuando se solicita info, no es necesario poner httpget
        public ActionResult Crear()
        {
            return View();
        }
        [HttpPost] //envia info al presiona el boton de crear
        public ActionResult Crear(Departamento dpto)
        {
            //metodo que envia los datos 
            try
            {
                if (dpto.NombreDepartamento == null)
                {
                    ModelState.AddModelError("", "Debe ingresar el nombre del departamento");
                    return View(dpto);
                }
                DepartamentoCN.Agregar(dpto);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ha ocurrido un error al agregar departamento ");
                return View(dpto);
            }
            //  return View();
        }
        public ActionResult GetDepartamento(int id)
        {
            var dpto = DepartamentoCN.GetDepartamento(id);
            return View(dpto);
        }
        public ActionResult Editar(int id)
        {
            var dpto = DepartamentoCN.GetDepartamento(id);
            return View(dpto);
        }
        [HttpPost] //envia info al presiona el boton de crear
        public ActionResult Editar(Departamento dpto)
        {
            try
            {
                if (dpto.NombreDepartamento == null)
                {
                    ModelState.AddModelError("", "Debe ingresar el nombre del departamento");
                    return View(dpto);
                }

                DepartamentoCN.Editar(dpto);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Debe ingresar el nombre del departamento");
                return View(dpto);
            }
        }
        public ActionResult Eliminar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var dpto = DepartamentoCN.GetDepartamento(id.Value);
            return View(dpto);
        }
        [HttpPost] //envia info al presiona el boton
        public ActionResult Eliminar(int id)
        {
            try
            {
                DepartamentoCN.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Error al eliminar");
                return View();
            }
        }
    }
}

WEB PROYECTOS/DEMO ASPNET MVC EN CAPAS/WEB_PROYECTOS/Views/Departamento/Crear.cshtml
@model ENTIDAD.Departamento

@{
    ViewBag.Title = "Crear Departamento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Crear Departamento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NombreDepartamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreDepartamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreDepartamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WEB PROYECTOS/DEMO ASPNET MVC EN CAPAS/WEB_PROYECTOS/Views/Departamento/Editar.cshtml
@model ENTIDAD.Departamento

@{
    ViewBag.Title = "Editar Departamento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Editar Departamento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartamentoId)

        <div class="form-group">
            @Html.LabelFor(model => model.NombreDepartamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreDepartamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreDepartamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WEB PROYECTOS/DEMO ASPNET MVC EN CAPAS/WEB_PROYECTOS/Views/Departamento/Eliminar.cshtml
@model ENTIDAD.Departamento

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>

<h3>¿Estas seguro de eliminar el departamento?</h3>
<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreDepartamento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreDepartamento)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

WEB PROYECTOS/DEMO ASPNET MVC EN CAPAS/WEB_PROYECTOS/Views/Departamento/GetDepartamento.cshtml
@model ENTIDAD.Departamento

@{
    ViewBag.Title = "GetDepartamento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
          Nombre de Departamento
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreDepartamento)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.DepartamentoId }) |
    @Html.ActionLink("Volver", "Index")
</p>

WEB PROYECTOS/DEMO ASPNET MVC EN CAPAS/WEB_PROYECTOS/Views/Departamento/Index.cshtml
@model IEnumerable<ENTIDAD.Departamento>

@{
    ViewBag.Title = "Lista de departametos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Departamentos</h2>

<p>
    @Html.ActionLink("Crear departamento", "Crear", "Departamento")
</p>
<table class="table">
    <tr>
        <th>
            Nombre de Departamento
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreDepartamento)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.DepartamentoId }) |
                @Html.ActionLink("Detalles", "GetDepartamento", new { id = item.DepartamentoId }) |
                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.DepartamentoId })
            </td>
        </tr>
    }

</table>